### ISSUE TITLE
Help with Integrating Zendure API in Home Assistant

### ISSUE THREAD

**Issue by lbouriez** [Zendure/developer-device-data-report#3]
Subject: Help with Integrating Zendure API in Home Assistant

Dear Zendure Support Team,

I have successfully obtained my appKey and secret from the API call, but I am unsure about how to use them in Home Assistant (HA). Currently, I have an MQTT setup in Home Assistant linked to the Mosquitto add-on. The devices typically publish to the add-on, as illustrated in the example below:

![image](https://user-images.githubusercontent.com/4749766/236206242-76052104-146c-4119-aed1-fd82b058e5cd.png)

In this context, could you please guide me through the process of subscribing to the Zendure MQTT URL? It is worth noting that in Home Assistant, we are only allowed to have one instance of an MQTT device. Therefore, I cannot add another one linked to Zendure without losing the current one.

I appreciate your assistance in helping me set up the integration with Zendure.

Best regards,

**Comment by lbouriez** [comment]
Answering to myself :)
I created a file called zendure.conf in the share/mosquito folder of HomeAssistant.
Inside this file I wrote:
```
connection external-bridge
address mqtt.zen-iot.com:1883
remote_username APPKEY
remote_password APPSECRET
clientid zendure

topic APPKEY/# both 0
```

I am now getting infos from the SuperBase into Mosquitto
![image](https://user-images.githubusercontent.com/4749766/236234731-dd6310a7-4b4f-492b-97a3-7c2947d6abb9.png)

**Comment by copadewe** [comment]
What did you enter as clientit in row 5?  really the word "zendure" or did you change it?
I did not get a connection.   APPKEY is clear change to the Key and passwort is also clear.
And topic "APPKEY" is also the same, change to the real Addkey.

**Comment by lbouriez** [comment]
My bad, last line, the topic mapping, replace zendure by zend. It seems that a long string doesn't work.

**Comment by copadewe** [comment]
I got respond from the server like you, it took a while but data will come in.
![grafik](https://user-images.githubusercontent.com/118108456/236432394-0af9eb95-dd28-4a5f-b53c-bc8aca64a80d.png)

**Comment by lbouriez** [comment]
Now for HA, the only way I know to integrate it it's to create a yml in the integration with the description of all the sensor...
I see that in each messages there is the config like HA expect, i was wondering if there was an easier way :?

**Comment by copadewe** [comment]
> 

I have no idea :-) will check with a partner at the weekend if we will find a solution on our own and come back.

**Comment by thomasbeaumont** [comment]
```
mqtt:
  sensor:
    - name: "zendure_outputPower"
      state_topic: "homeassistant/zend/cFR86vRs/1LgQua1F/state"
      unit_of_measurement: "W"
      value_template: "{{ value_json.outputPower }}"
```

Gives me this:

![Screenshot 2023-05-14 at 14 27 44](https://github.com/Zendure/developer-device-data-report/assets/29218640/9eff465a-ebbe-460f-b47d-dfcba05247bc)

I guess we have to do it for every value...

**Comment by thomasbeaumont** [comment]
But this should work, including switches... from the screenshot they already done something similar in HA but haven't shared it yet? Thanks lads for the help with MQTT by the way

**Comment by lbouriez** [comment]
Here my own configuration for all the sensors:
```yml
mqtt:
  sensor:
    - name: "Zendure - Electric Level"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "%"
      device_class: "battery"
      value_template: "{{ value_json.electricLevel }}"
      unique_id: 5d54cc6d-8e56-4d76-bacd-2f361e4a7213

    - name: "Zendure - Remaining Out Time"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "MIN"
      value_template: "{{ value_json.remainOutTime }}"
      unique_id: 674c070a-93f9-4f51-b1b7-6f1247f043e0

    - name: "Zendure - Remaining Input Time"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "MIN"
      value_template: "{{ value_json.remainInputTime }}"
      unique_id: a46cc9f3-c4b6-4ff1-9b47-6b344ce439b3

    - name: "Zendure - Soc Set"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "%"
      value_template: "{{ value_json.socSet }}"
      unique_id: e151f81a-8e60-4ae6-a3e5-c82f7a6f03f4

    - name: "Zendure - Battery Capacity"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.batterCapacity }}"
      unique_id: ee2b4fc4-3a9b-4ff7-a57e-0b5f9e7f81cc

    - name: "Zendure - AC Input Limit"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      value_template: "{{ value_json.acInputLimit }}"
      unique_id: a10efc5f-39d4-44d9-8e5a-2e6c344fdcd1

    - name: "Zendure - Slow Charger Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      device_class: "power"
      value_template: "{{ value_json.slowChargePower }}"
      unique_id: e868d82d-68cd-4c45-9e3c-dcf6d0b7a221

    - name: "Zendure - Input Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      device_class: "power"
      value_template: "{{ value_json.inputPower }}"
      unique_id: d1aeb372-6493-43b2-8f23-96c6d94c5d70

    - name: "Zendure - AC Input Mode"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.acInputMode }}"
      unique_id: d2442aa3-7bb4-4283-93d7-76aaf8b1ffaf

    - name: "Zendure - AC Input Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      value_template: "{{ value_json.acInputPower }}"
      unique_id: e5ae0645-2b82-4c02-9d66-f55f28c3ad97

    - name: "Zendure - AC Frequency"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.acHz }}"
      device_class: frequency
      unique_id: ad6ce26b-3734-4d3b-832f-5d2c19a1080d

    - name: "Zendure - AC Input Voltage"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "V"
      value_template: "{{ value_json.acInputVoltage }}"
      device_class: voltage
      unique_id: 705692b1-5a47-4d09-b7b9-1843c3d9d1d9

    - name: "Zendure - AC Output Mode"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.acOutputMode }}"
      unique_id: c87b1412-2f16-4e66-9655-080abdb10fb4

    - name: "Zendure - AC Output Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      value_template: "{{ value_json.acOutputPower }}"
      device_class: power
      unique_id: fa932255-ec79-4f8a-9612-b12a74176952

    - name: "Zendure - AC Output Voltage"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "V"
      value_template: "{{ value_json.acOutputVoltage }}"
      device_class: voltage
      unique_id: 16590c9b-327e-4a71-a0c6-c63b51cc7d64

    - name: "Zendure - AC Output Factor"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.acOutputFactor }}"
      unique_id: 7e5f8f2a-14a5-4684-9917-8114a66b5722

    - name: "Zendure - DC Input Mode"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.dcInputMode }}"
      unique_id: 64770707-44f9-4e33-bd09-2c90a0cc5b4c

    - name: "Zendure - DC Input Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      device_class: power
      value_template: "{{ value_json.dcInputPower }}"
      unique_id: f94c735a-6df4-4f0c-9c11-19a8b0f0f9b7

    - name: "Zendure - Output Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      device_class: power
      value_template: "{{ value_json.outputPower }}"
      unique_id: f5ff1b9d-2a66-4196-90c7-97e1a0133da2

    - name: "Zendure - DC Output Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      device_class: power
      value_template: "{{ value_json.dcOutputPower }}"
      unique_id: 947d2007-35b7-4dfe-bd9b-4113585230f7

    - name: "Zendure - Circle Output Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      value_template: "{{ value_json.circleOutputPower }}"
      unique_id: e335d6b5-c2e0-4c49-872d-8e1b70d17a0d

    - name: "Zendure - USB 1 Output Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      value_template: "{{ value_json.usb1OutputPower }}"
      unique_id: 0dd35b0c-4312-459a-9c8b-08d5a0de1ac7

    - name: "Zendure - USB 2 Output Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      value_template: "{{ value_json.usb2OutputPower }}"
      unique_id: ef8e07ab-5a7d-4b70-9ef5-4c79f0a98f4b

    - name: "Zendure - Type-C 1 Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      value_template: "{{ value_json.typec1Power }}"
      unique_id: 0b2b3f56-2f3e-446b-98a4-1a952a4d00a3

    - name: "Zendure - Type-C 2 Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      value_template: "{{ value_json.typec2Power }}"
      unique_id: 9b43af49-c6b6-4da4-8e3d-68d525b78481

    - name: "Zendure - Type-C 3 Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      value_template: "{{ value_json.typec3Power }}"
      unique_id: 7027a57b-3d64-4e2f-b90d-2a8cb06ea891

    - name: "Zendure - Type-C 4 Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      value_template: "{{ value_json.typec4Power }}"
      unique_id: 0a54d710-3f60-431a-b4ef-97a7a35a0812

    - name: "Zendure - Anderson Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      value_template: "{{ value_json.andersonPower }}"
      unique_id: 38f0f847-2f88-4ae7-9477-2bbd0f7be2d1

    - name: "Zendure - Ambient Light Mode"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      device_class: illuminance
      value_template: "{{ value_json.ambientLightMode }}"
      unique_id: be2fc100-4a66-41fc-86e0-28b6ac6d739b

    - name: "Zendure - Ambient Light Color"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      device_class: illuminance
      value_template: "{{ value_json.ambientLightColor }}"
      unique_id: a4a27284-0d53-4184-8e75-68755c5a7d48

    - name: "Zendure - Ambient Light Ness"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      device_class: illuminance
      value_template: "{{ value_json.ambientLightNess }}"
      unique_id:

    - name: "Zendure - Assist Angle"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.assistAngle }}"
      unique_id:

    - name: "Zendure - Lamp Mode"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      device_class: illuminance
      value_template: "{{ value_json.lampMode }}"
      unique_id: dc2b9e2d-eeb9-4b9e-bbc1-2f3e60115e01

    - name: "Zendure - UPS Mode"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.upsMode }}"
      unique_id: 2e7f85e2-3a3e-437e-b0e2-36f74ee8a3c2

    - name: "Zendure - Machine Stand Time"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "MIN"
      value_template: "{{ value_json.machineStandTime }}"
      unique_id: f6b3eafa-3f16-4de4-877a-7b60f03dbd32

    - name: "Zendure - Screen Stand Time"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "MIN"
      value_template: "{{ value_json.screenStandTime }}"
      unique_id: b9de0f39-f9d7-4ed6-9458-0a51a15b3b3a

    - name: "Zendure - Wi-Fi Signal Level"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.wifiSignalLevel }}"
      unique_id: 85d2b3ac-d3a2-4099-bbb9-972c7b6d202d

    - name: "Zendure - Blue State"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.blueState }}"
      unique_id: a64b199c-3d25-4e14-b1d6-5840d9324b3c

    - name: "Zendure - Wi-Fi State"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.wifiState }}"
      unique_id: a7e70381-7d59-4d6e-8a50-978f976dc2ed

    - name: "Zendure - Silent Input"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.silentInput }}"
      unique_id: baa3eb42-3b2b-45f2-a2fb-dfe68ff3f3b4

    - name: "Zendure - Amp Up"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.ampUp }}"
      unique_id: c32741d7-3e76-4dbd-bef9-3d8b8bba4aeb

    - name: "Zendure - DC Hardware Version"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.dcHardwareVersion }}"
      unique_id: c53b3425-4c39-4a76-883f-1a3e816aad3d

    - name: "Zendure - AC Hardware Version"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.acHardwareVersion }}"
      unique_id: e8e15ee5-b388-432f-b03e-3f4f7dd7a3ae

    - name: "Zendure - BMS Hardware Version"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.bmsHardwareVersion }}"
      unique_id: 2f0c7f89-6e17-4d94-ae5e-5401f5e19a4f

    - name: "Zendure - Master Hardware Version"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.masterHardwareVersion }}"
      unique_id: 8e876825-3b69-4967-a4fe-3d4c92050bcf

    - name: "Zendure - Type-C Hardware Version"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.typecHardwareVersion }}"
      unique_id: 198f49c5-6b0e-46dd-94a5-ae8700ae15de

    - name: "Zendure - Electric Fan State"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.electricFanState }}"
      unique_id: e84f76e0-6e17-429f-bd91-5e422b3662f5

    - name: "Zendure - Battery Number"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.batteryNum }}"
      unique_id: 42d1f4f7-72c6-4390-a7b9-3f586dd24ee6

    - name: "Zendure - Temperature"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "K"
      device_class: "temperature"
      value_template: "{{ value_json.temperature }}"
      unique_id: 7be1db4a-4f56-4775-8e0c-9b6f254f1f03

    - name: "Zendure - Solar Work Mode"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.solarWorkMode }}"
      unique_id: 2852c790-14ee-4dd2-94d5-1d4ab9b7a1d6

    - name: "Zendure - Solar Work Output Voltage"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "V"
      device_class: "voltage"
      value_template: "{{ value_json.solarWorkOutputVoltage }}"
      unique_id: f92ddcca-95e3-457e-81f2-c7c4e3e6bcf4

    - name: "Zendure - Solar Output Power"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      unit_of_measurement: "W"
      device_class: "power"
      value_template: "{{ value_json.solarOutputPower }}"
      unique_id: 5dc33abf-81b3-43c1-9242-87152f2d021a

    - name: "Zendure - Assist Double Flash"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.assistDoubleFlash }}"
      unique_id: 1a3988b5-9563-4c50-b1b2-44d9c7ff06a0

    - name: "Zendure - Series Mode"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.seriesMode }}"
      unique_id: e8df1831-8e5d-4dc2-8c81-7850c24976f0

    - name: "Zendure - Parallel Mode"
      state_topic: "zend/2jb18H4f/1VaC4Eq1/state"
      value_template: "{{ value_json.parallelMode }}"
      unique_id: c4a9d8a3-16a6-4b16-bff1-ff6c1d51fb62

```

You need to change the state_topic by your own.

You will get the sensors in HA
![image](https://github.com/Zendure/developer-device-data-report/assets/4749766/555387ed-637a-4592-b95c-3bebae851a2e)
Now missing the switches :)
